// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250602205212_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(131080)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            Content = "This is the content for the first post. Kinda cool eh?",
                            Title = "First Post"
                        },
                        new
                        {
                            PostID = 2,
                            Content = "Well, this is awkward... not sure what to do.",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostID = 3,
                            Content = "Der Post ist eine kleine Scheisse Post",
                            Title = "Poste Drei"
                        },
                        new
                        {
                            PostID = 4,
                            Content = "Merde! En Francais d'accord?",
                            Title = "Un Post Quatre"
                        },
                        new
                        {
                            PostID = 5,
                            Content = "So... Beethoven or Liquor?",
                            Title = "A fifth of Post"
                        },
                        new
                        {
                            PostID = 6,
                            Content = "The number of sick sheep in a bad tongue twister",
                            Title = "Six"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
